#!/bin/sh
##
# Generate a ZID, which is a secure random lowercase hex string.
#
# Usage:
#
#     zid [n]
#
# Options:
#
#   * `n` is the number of bits; in this implementation.
#     Default is 128 bits a.ka. 16 bytes a.k.a. 32 characters.
#     The number of bits must be a multiple of 8.
#
# Example:
#
#     $ zid 128
#     0cb49f132271bf0436a8f0689f87ee9c
#
# Alternate solution for Linux, using the tr command:
#
#     cat /dev/urandom | tr -cd '0-9a-f' | head -c 16; echo
#
# Alternate solution for BSD and Mac OS X, using the tr command:
#
#     cat /dev/urandom | env LC_CTYPE=C tr -cd '0-9a-f' | head -c 16; echo
#
# This implemenation uses the commands `hexdump` and `/dev/urandom`.
#
# Version: 3.0.0
# Created: 2015-01-25
# Updated: 2016-06-20
# License: Any of GPL, LGPL, MIT, BSD
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
bits=${1-128}
n=$(expr $bits / 8)
hexdump -n $n -v -e '/1 "%02x"' -e "/$n \"\n\"" /dev/urandom
